#Para cambiar el nombre en la importacion, asi aclaramos y evitamos conflictos con futuras importaciones
from .Bolsones import Bolson as BolsonResource
from .Bolsones import Bolsones as BolsonesResource
from .BolsonesVenta import BolsonVenta as BolsonVentaResource
from .BolsonesVenta import BolsonesVenta as BolsonesVentaResource
from .BolsonesPendientes import BolsonPendiente as BolsonPendienteResource
from .BolsonesPendientes import BolsonesPendientes as BolsonesPendientesResource
from .BolsonesPrevios import BolsonPrevio as BolsonPrevioResource
from .BolsonesPrevios import BolsonesPrevios as BolsonesPreviosResoruce
from .Productos import Producto as ProductoResource
from .Productos import Productos as ProductosResource
from .Compras import Compra as CompraResource
from .Compras import Compras as ComprasResource
from .Clientes import Cliente as ClienteResource
from .Clientes import Clientes as ClientesResource
from .Proveedores import Proveedor as ProveedorResoruce
from .Proveedores import Proveedores as ProveedoresResource
from .ProductosBolsones import ProductoBolson as ProductoBolsonResource
from .ProductosBolsones import ProductosBolsones as ProductosBolsonesResource
